version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: suryanarayanaant/ctf-backend:latest  # Add this line
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=session_secret
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: suryanarayanaant/ctf-frontend:latest  # Add this line
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://backend-service.onrender.com/api
    depends_on:
      - backend
